import { useRef, useState } from "react";
import { getImageUrl, getTVSeason } from "../api/tmdb";
export default function SeasonExplorer({ tvId, seasons=[] }) {
 const [selected,setSelected]=useState(null), [data,setData]=useState(null), [loading,setLoading]=useState(false), [error,setError]=useState("");
 const cache=useRef(new Map());
 async function open(season){ setSelected(season); setError(""); const cached=cache.current.get(season.season_number); if(cached){setData(cached);return;} setLoading(true); setData(null); try{const value=await getTVSeason(tvId,season.season_number); cache.current.set(season.season_number,value);setData(value)}catch(e){setError(e.message||"Season could not be loaded.")}finally{setLoading(false)} }
 return <div className="mt-8"><h3 className="text-xl font-black">Seasons</h3><div className="movie-row mt-4 flex gap-4 overflow-x-auto pb-4">{seasons.map(s=><button key={s.id} type="button" onClick={()=>open(s)} aria-expanded={selected?.id===s.id} className="w-44 shrink-0 rounded-2xl border border-white/10 bg-[#11151c] p-3 text-left hover:border-red-500/40">{s.poster_path&&<img src={getImageUrl(s.poster_path,"w185")} alt="" loading="lazy" width="185" height="278" className="aspect-[2/3] w-full rounded-xl object-cover"/>}<span className="mt-3 block font-bold">{s.season_number===0?"Specials":s.name}</span><span className="mt-1 block text-xs text-gray-400">{s.episode_count} episodes{s.air_date?` · ${s.air_date.slice(0,4)}`:""}</span></button>)}</div>
 {selected&&<section className="mt-5 rounded-3xl border border-white/10 bg-white/[0.03] p-5" aria-live="polite"><div className="flex items-center justify-between gap-3"><h4 className="text-xl font-black">{selected.season_number===0?"Specials":selected.name}</h4><button className="min-h-11 rounded-xl border border-white/10 px-4 text-sm font-bold" onClick={()=>{setSelected(null);setData(null)}}>Close</button></div>{loading&&<p className="mt-5 text-gray-400">Loading episodes…</p>}{error&&<div className="mt-5"><p className="text-red-300">{error}</p><button className="mt-3 rounded-lg bg-red-600 px-4 py-2 font-bold" onClick={()=>open(selected)}>Retry</button></div>}{!loading&&!error&&data&&<div className="mt-5 grid gap-3">{(data.episodes||[]).map(e=><article key={e.id} className="grid gap-4 rounded-2xl border border-white/10 p-4 sm:grid-cols-[160px_1fr]">{e.still_path&&<img src={getImageUrl(e.still_path,"w300")} alt="" loading="lazy" width="300" height="169" className="aspect-video w-full rounded-xl object-cover"/>}<div><p className="text-xs font-bold uppercase tracking-wider text-red-400">Episode {e.episode_number}</p><h5 className="mt-1 font-black">{e.name}</h5><p className="mt-1 text-xs text-gray-400">{[e.air_date,e.runtime?`${e.runtime} min`:null,e.vote_average?`${e.vote_average.toFixed(1)}/10`:null].filter(Boolean).join(" · ")}</p>{e.overview&&<p className="mt-2 line-clamp-3 text-sm leading-6 text-gray-300">{e.overview}</p>}</div></article>)}{!(data.episodes||[]).length&&<p className="text-gray-400">No episode information is available for this season.</p>}</div>}</section>}</div>;
}
